version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: airflow_postgres
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: airflow_redis
    restart: always
    ports:
      - "6379:6379"

  airflow:
    image: apache/airflow:latest
    container_name: airflow_etl
    restart: always
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__WEBSERVER__RBAC=True
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__AUTH_BACKEND=airflow.contrib.auth.backends.password_auth
      - _AIRFLOW_WWW_USER_CREATE=True
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./firebase/firebase_credentials.json:/opt/airflow/firebase_credentials.json 
    ports:
      - "8080:8080"
    command: webserver
    depends_on:
      - postgres
      - redis

  etl_worker:
    build: .
    container_name: etl_worker
    restart: always
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    command: python /app/airflow/dags/etl_dag.py

  firebase:
    image: node:18  # Node.js is required for Firebase Emulator
    container_name: firebase_rtdb_emulator
    restart: always
    volumes:
      - ./firebase:/etl_pipeline_demo
    working_dir: /etl_pipeline_demo
    command: ["firebase", "emulators:start", "--only", "database,firestore,auth"]
    ports:
      - "8085:8085"  # Firestore emulator
      - "9099:9099"  # Firebase Auth emulator
      - "9000:9000"  # Realtime Database emulator

volumes:
  postgres_data:
  firebase_data:
