name: Connect to an AWS role from a GitHub repository

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: "us-east-1"

permissions:
  id-token: write
  contents: read

jobs:
  ConnectToAWS:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Assume AWS Role via OIDC
        run: |
          export AWS_ROLE_ARN="arn:aws:iam::586794441233:role/awsToGithub"
          export AWS_WEB_IDENTITY_TOKEN=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
                                          "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value')

          export CREDENTIALS=$(aws sts assume-role-with-web-identity \
            --role-arn "$AWS_ROLE_ARN" \
            --role-session-name "GithubActionsSession" \
            --web-identity-token "$AWS_WEB_IDENTITY_TOKEN" \
            --duration-seconds 3600)

          export AWS_ACCESS_KEY_ID=$(echo $CREDENTIALS | jq -r '.Credentials.AccessKeyId')
          export AWS_SECRET_ACCESS_KEY=$(echo $CREDENTIALS | jq -r '.Credentials.SecretAccessKey')
          export AWS_SESSION_TOKEN=$(echo $CREDENTIALS | jq -r '.Credentials.SessionToken')

      - name: Verify AWS Identity
        run: |
          aws sts get-caller-identity