name: Deploy Chatbot to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install AWS CLI & Terraform
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli terraform

      - name: Deploy to AWS Elastic Beanstalk
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve
