name: Deploy About Me Chatbot to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Create Virtual Environment and Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip setuptools wheel
          pip install -r assets/projects/about-me-chat-bot/requirements.txt --target .
          cp assets/projects/about-me-chat-bot/requirements.txt .

      - name: Set AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          export AWS_REGION=us-east-1
          aws configure list
          aws sts get-caller-identity

      - name: Install AWS Elastic Beanstalk CLI
        run: |
          pip install --upgrade awsebcli
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          eb --version

      - name: Package and Deploy from `assets/projects/about-me-chat-bot`
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
        run: |
          cd assets/projects/about-me-chat-bot
          zip -r application.zip . -x "*.git*" "venv/*" "*.DS_Store"
          mv application.zip ../../..
          eb deploy about-me-chat-bot-env --timeout 20 --region us-east-1